### ISSUE TITLE
It doesn't work with Highcharts v9

### ISSUE THREAD

**Issue by ver1000000** [highcharts/map-from-svg#4]
[The converter](https://highcharts.github.io/map-from-svg/) doesn't support v9.

I had to clone and change links to the previous version to make it work:
```
<!-- Include Highcharts -->
<script src="https://code.highcharts.com/maps/8.1/highmaps.js"></script>
<script src="https://code.highcharts.com/8.1/modules/data.js"></script>```

**Comment by Rielbe** [comment]
Thanks for the workaround. Hope this will be fixed

**Comment by KacperMadej** [comment]
Thank you for reporting the problem - it should be fixed within the next few days.
