### ISSUE TITLE
Highcharts maps from SVG sources does not work.

### ISSUE THREAD

**Issue by magdalena-gut** [highcharts/map-from-svg#5]
#### Expected behaviour
Map parser should allow to load SVGs and convert to JSON.

#### Actual behaviour
No possibility of generating JSON, errors in the console.

#### Live demo with steps to reproduce
Paste your SVG markup in the text area. Hit the Load button and then "View Highcharts Maps config".
https://highcharts.github.io/map-from-svg/

#### Product version
v. 9.3

#### Affected browser(s)
N/A

**Comment by KacperMadej** [comment]
_Internal note:_
Probably a duplicate of https://github.com/highcharts/map-from-svg/issues/4
